feat: refactor job
Qbox-project/qbx_policejob pull request #112
Opened 2024-05-28 16:21 UTC by ArturMichalak

## Description

The changes were inspired by spikes not working with qbx:bucketlockdownmode other than “inactive”.
The modification began with the optimization of spikes. Then the changes to spikes were integrated into object creation. Locales were changed to be compatible with the project standards. The “i” loop was applied, wherever it makes sense. Moved the plate prefix “LSPD” to the configuration. 

Refactor is still in development, but invite you to test and verify the source code.

## Checklist

- [X] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [X] My pull request fits the contribution guidelines & code conventions.

2024-05-28 21:43 UTC, ArturMichalak commented
In this commit https://github.com/Qbox-project/qbx_policejob/pull/112/commits/4cb898952aa065702baa9fb1206f607235be1f7d
a change from this PR was used https://github.com/Qbox-project/qbx_policejob/pull/86
Thanks to [bicatcho11](https://github.com/bicatcho11) for the PR.

2024-05-29 06:44 UTC, ArturMichalak commented
Should https://github.com/Qbox-project/qbx_policejob/pull/81 be integrated with this PR?

2024-05-29 08:16 UTC, Manason commented
> Should #81 be integrated with this PR?

This PR is already massive. Maybe do it in a separate one?

2024-05-30 08:26 UTC, Manason requested changes
The refactoring code should be split from the new code. If it's too difficult to do so at this point fine, but please keep PRs small in the future as this is too large to review properly.

2024-05-30 08:26 UTC, Manason commented on client/interactions.lua
> +    RemoveAnimDict('mp_arresting')
lib.playAnim has the same parameters as TaskPlayAnim, but does the request and remove.
```suggestion
    lib.playAnim(cache.ped, 'mp_arresting', 'idle', 8.0, -8, -1, cuffType, 0, false, false, false)
```

2024-05-30 08:26 UTC, Manason commented on client/interactions.lua
> +            lib.disableControls:Add(
I'm not convinced that using lib.disableControls is more readable than the previous way of disabling controls.

2024-05-30 08:26 UTC, Manason commented on client/objects.lua
> +local function silentWaitFor(cb, timeout)
What is the difference between this and lib.waitFor?

2024-05-30 08:26 UTC, Manason commented on client/objects.lua
> +RegisterNetEvent('police:client:SpawnSpikeStrip', function()
Is this a new net event? Where did this used to be?

2024-05-30 08:26 UTC, Manason commented on client/objects.lua
> +end)
Do we need an infinite loop to check this? An improvement would be using a point or a lib zone to only be checking when near a spike strip.

2024-05-30 08:26 UTC, Manason commented on client/objects.lua
> +local function watchInVehicle(vehicle)
What does this function name mean?

2024-05-30 13:57 UTC, ArturMichalak commented on client/objects.lua
> +local function silentWaitFor(cb, timeout)
This function doesn't throw errors on timeout. The occurrence of such a situation should not be considered an error in this case.

2024-05-30 14:00 UTC, ArturMichalak commented on client/objects.lua
> +RegisterNetEvent('police:client:SpawnSpikeStrip', function()
Nope. "spikestrip" command

2024-05-30 14:06 UTC, ArturMichalak commented on client/objects.lua
> +end)
At this moment yes, in the future it can be changed to zones. 
Originally it looked like this:
```lua
CreateThread(function()
    if IsLoggedIn then
        GetClosestSpike()
    end
    Wait(500)
end)
```

2024-05-30 14:07 UTC, ArturMichalak commented on client/objects.lua
> +local function watchInVehicle(vehicle)
I am looking for a name that would describe well the observation of spikestrips relative position to the tires of the vehicle the player is driving.

2024-05-30 14:11 UTC, ArturMichalak commented
>The refactoring code should be split from the new code. If it's too difficult to do so at this point fine, but please keep PRs small in the future as this is too large to review properly.

I know, the most messy part is the locales conversion.

2024-05-30 14:12 UTC, ArturMichalak commented on client/interactions.lua
> +    RemoveAnimDict('mp_arresting')
I'd prefer to put it in the next PR so as not to confuse more

2024-05-30 14:28 UTC, ArturMichalak commented on client/interactions.lua
> +            lib.disableControls:Add(
I moved the controls to a variable, now it should make more sense.
Moreover, a centrally controlled actions deactivation sounds like a good plan.

2024-05-30 14:48 UTC, Manason commented on client/objects.lua
> +local function silentWaitFor(cb, timeout)
Maybe better to re-use lib.waitFor and use a pcall to catch the error and ignore it? Up to you.

2024-05-30 16:07 UTC, ArturMichalak commented on client/objects.lua
> +local function silentWaitFor(cb, timeout)
sounds good

2024-05-31 10:36 UTC, ArturMichalak commented
there is no need to slim it down more

2024-05-31 10:37 UTC, ArturMichalak commented on client/objects.lua
> +local function watchInVehicle(vehicle)
renamed to burstTireCloseToSpike

2024-05-31 20:26 UTC, Manason approved these changes
Skimmed remaining changes. Seems like an overall improvement

2024-05-31 21:30 UTC, ArturMichalak commented on client/objects.lua
> +            if w ~= -1 then wheels[#wheels + 1] = { wheel = w, index = i - 1 } end
done

2024-05-31 21:34 UTC, ArturMichalak commented on client/objects.lua
> +local function watchInVehicle(vehicle)
It doesn't return a value, so check or detect could be confusing

2024-06-01 05:06 UTC, merged