Enhanced Localization and Configurable Handcuff Breaking Feature
Qbox-project/qbx_policejob pull request #117
Opened 2024-05-31 20:23 UTC by cosminwindox

## Description

This pull request introduces the ability to break handcuffs using a skill check through the ox_lib. Additionally, I have enhanced the project's localization by adding the English translation for the new notification and updating the Portuguese translation to a more formal version, ensuring all remaining texts are translated. For users who prefer the original functionality, this feature can be disabled in the client config, allowing the system to operate as before. 

## Checklist

- [X] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [X] My pull request fits the contribution guidelines & code conventions.

2024-05-31 21:36 UTC, ArturMichalak commented
separate PR for translations is preferred

2024-06-01 17:15 UTC, ArturMichalak commented on client/interactions.lua
> +                    cuffType = 48
try not to duplicate lines
```lua
cuffType = 48
exports.qbx_core:Notify(locale('info.cuffed_walk'), 'success')
```

It looks like you can use return here

2024-06-01 17:23 UTC, ArturMichalak requested changes

2024-06-01 17:23 UTC, ArturMichalak commented on client/interactions.lua
> +                    exports.qbx_core:Notify(locale('success.escapedcuff'), 'success')
try not to duplicate lines
```lua
cuffType = 48
exports.qbx_core:Notify(locale('info.cuffed_walk'), 'success')
```

It looks like you can use return here

2024-06-01 17:23 UTC, ArturMichalak commented on client/interactions.lua
> +                local SkillCheckSuccess = lib.skillCheck(config.SkillCheckDifficulty, config.SkillCheckInputs)
```suggestion
                local isSuccess = lib.skillCheck(config.SkillCheckDifficulty, config.SkillCheckInputs)
```

2024-06-01 17:23 UTC, ArturMichalak commented on client/interactions.lua
> +                if skillchecksuccess == true then
```suggestion
                if isSuccess then
```

2024-06-01 17:23 UTC, ArturMichalak commented on client/interactions.lua
> +            getCuffedAnimation(playerId)
Are you sure this is the right place to call this animation?

2024-06-01 17:37 UTC, cosminwindox commented on client/interactions.lua
> +            getCuffedAnimation(playerId)
In my understanding, I think this is the most accurate because the player starts to be handcuffed with the animation, and then, if they use the skill check, they are released. If it is disabled, they are handcuffed. Do you have a better idea?

2024-06-01 17:48 UTC, cosminwindox commented on client/interactions.lua
> +                    exports.qbx_core:Notify(locale('success.escapedcuff'), 'success')
Done. thanks.

2024-06-01 20:19 UTC, ArturMichalak requested changes

2024-06-01 20:19 UTC, ArturMichalak commented on client/interactions.lua
> +            getCuffedAnimation(playerId)
Will the animation work when the soft handcuffs are on?

2024-06-01 20:19 UTC, ArturMichalak commented on client/interactions.lua
> +                    exports.qbx_core:Notify(locale('success.escapedcuff'), 'success')
You misunderstood the suggestion. This block should be thrown outside the config.SkillCheck condition. Then the isSuccess block should end with return.

2024-06-01 21:03 UTC, cosminwindox commented on client/interactions.lua
> +                    exports.qbx_core:Notify(locale('success.escapedcuff'), 'success')
I revised the script logic by altering the sequence of the skill check verification. Now, if the skill check passes, the code immediately exits after the successful escape action; otherwise, it continues with the normal flow of the code.
Also undo the changed in the animation location.

2024-06-01 21:03 UTC, cosminwindox reviewed
I revised the script logic by altering the sequence of the skill check verification. Now, if the skill check passes, the code immediately exits after the successful escape action; otherwise, it continues with the normal flow of the code.
Also undo the changes in the animation location.

2024-06-01 21:12 UTC, cosminwindox reviewed
little fix

2024-06-01 22:14 UTC, ArturMichalak commented
The condition looks much better. Still, the names in the configuration are not descriptive enough. You can also change the notation of config keys to camelCase.

2024-06-01 22:14 UTC, ArturMichalak approved these changes

2024-06-01 22:18 UTC, ArturMichalak commented
client/interactions.lua:369:16: line contains trailing whitespace

2024-06-01 22:35 UTC, cosminwindox reviewed
Removed the trailing whitespace on line 369 of client/interactions.lua.
Updated the configuration variable names to camelCase and renamed them for better understanding.

2024-06-12 03:54 UTC, mafewtm approved these changes

2024-06-12 03:55 UTC, mafewtm commented on client/interactions.lua
> +            getCuffedAnimation(playerId)
This needs to be sorted before this can be merged.

2024-06-20 14:33 UTC, merged