refactor: switch from utils to lib
Qbox-project/qbx_policejob pull request #74
Opened 2024-01-16 03:37 UTC by MafewTM

## Description

Switch from the deprecated utils module to the new lib module

_Don't merge this until the new lib module is finished and the new core is released_

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-01-16 05:10 UTC, solareon requested changes

2024-01-16 05:10 UTC, solareon commented on client/job.lua
> +    TriggerServerEvent('inventory:server:addTrunkItems', qbx.getVehiclePlate(veh), config.carItems)
```suggestion
```
Pretty sure this isn't a thing anymore

2024-01-16 05:12 UTC, solareon approved these changes

2024-01-20 17:51 UTC, Molicheu approved these changes

2024-01-20 18:15 UTC, merged