Adding some new events
Qbox-project/qbx_policejob pull request #80
Opened 2024-01-26 13:27 UTC by 1Evolve

## Description

1. When activated, this event checks the bank account of the nearest layer and sends the data to the server
2. When activated, this event checks the licenses of the nearest player and sends the data to the server
3. When activated, this event seizes the driver's license of the nearest player and sends the data to the server.

Please note that these events are designed to be part of the in-game police scenario, enabling them to perform actions such as checking bank accounts, licenses, and seizing driver's licenses effectively.

At another time, some events will be
1. added, such as: Check whether the player has unpaid bills
2. The player's mask is removed by the policeman

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-01-26 20:17 UTC, Manason requested changes
Could you address more details of this proposed set of features? How would users interact with other players? Command? Radial menu? 3rd eye?

I'm curious as to what other people think of these proposed features, but at the very least I would want them gated behind config option to enable them (default disabled).

To address the actual code structure, I'm not seeing a need/use for the client event handlers. It seems like the server has all the information needed already.

2024-01-26 21:47 UTC, 1Evolve commented
> Could you address more details of this proposed set of features? How would users interact with other players? Command? Radial menu? 3rd eye?
> 
> I'm curious as to what other people think of these proposed features, but at the very least I would want them gated behind config option to enable them (default disabled).
> 
> To address the actual code structure, I'm not seeing a need/use for the client event handlers. It seems like the server has all the information needed already.

When approved, it will be added to radial menu

2024-01-27 08:39 UTC, 1Evolve commented
https://github.com/Qbox-project/qbx_radialmenu/pull/44

2024-01-27 15:59 UTC, MafewTM commented
I don't think police being able to check peoples bank accounts is a feature that should be added nor should it be a radial menu option either. And for the seizing of licenses, this is already available through the revocation of licenses.

2024-01-27 21:59 UTC, TonybynMp4 commented
+1 on what matthew said + let's stop doing things on the 'closest' player, we can target a specific player, just use that..

2024-02-12 17:24 UTC, closed without merging