rewrite camera code and switch to lib
Qbox-project/qbx_policejob pull request #81
Opened 2024-01-26 23:27 UTC by 1Evolve

## Description

Rewrite the camera code
With the addition of new codes, and adjusting the code in a better way It is now easier to add new cameras to the code
Add a list of all cameras with numbers, names and addresses Add a tablet and animation when opening the camera andyy code

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-01-27 08:39 UTC, 1Evolve commented
https://github.com/Qbox-project/qbx_radialmenu/pull/44

2024-02-03 19:11 UTC, 1Evolve commented
for add new camera easy using this code 

```
RegisterCommand('draw', function()
    if isInitialCast then return end
    isInitialCast = true
    lib.hideTextUI()
    lib.showTextUI('[E] - Copy Coords', { position = "left-center", })
    CreateThread(function() 
        while isInitialCast do
            local hit, _, hitCoords, _, _ = lib.raycast.cam(1, 4, 10)
            
            if hit then
                local playerHeadCoords = GetPedBoneCoords(cache.ped, 31086, 0, 0, 0)
                DrawLine(playerHeadCoords.x, playerHeadCoords.y, playerHeadCoords.z, hitCoords.x, hitCoords.y, hitCoords.z, 29, 21, 237, 255)
                DrawSphere(hitCoords.x, hitCoords.y, hitCoords.z, 0.05, 29, 21, 237, 0.85)
                if IsControlJustPressed(0, 38) then
                    initialCoords = hitCoords
                    lib.hideTextUI()
                    isInitialCast = false
                    print(initialCoords.x, initialCoords.y, initialCoords.z, initialCoords.w)
                end
            end
        end
    end)
end, false)
```

2024-02-19 12:22 UTC, BerkieBb requested changes

2024-02-19 12:22 UTC, BerkieBb commented on config/client.lua
> +        [49] = {coords = vec4(458.513, -1017.173, 31.428, 53.63), label = 'Los Santos Police Department - CAM#2', isOnline = true},
These numbers in front are not necessary, lua adds these automatically and in vscode you can enable in the lua extension to show these as hints instead.

2024-02-19 12:22 UTC, BerkieBb commented on client/camera.lua
> +        Wait(1)
Never wait 1, remember? Wait(0) for every frame stuff

2024-02-19 12:22 UTC, BerkieBb commented on client/camera.lua
> +    ClearPedTasks(PlayerPedId())
cache.ped can be used here

2024-02-19 12:22 UTC, BerkieBb commented on client/camera.lua
> +            table.insert(menu.options, {
Use `menu.options[#menu.options + 1] =` instead of table.insert

2024-02-19 12:22 UTC, BerkieBb commented on client/camera.lua
> +    cameraId = tonumber(cameraId)
Put this above the local coords so you don't tonumber twice

2024-02-19 12:22 UTC, BerkieBb commented on client/camera.lua
> +        local CamRot = GetCamRot(securityCam, 2)
camelCase

2024-02-19 12:22 UTC, BerkieBb commented on client/camera.lua
> +local InsideCam = false
camelCase

2024-02-19 12:22 UTC, BerkieBb commented on server/commands.lua
> +    TriggerClientEvent('police:client:showcamera', source)
camelCase

2024-02-19 18:32 UTC, 1Evolve commented on server/commands.lua
> +    TriggerClientEvent('police:client:showcamera', source)
done :)

2024-02-19 18:32 UTC, 1Evolve commented on client/camera.lua
> +local InsideCam = false
done :)

2024-02-19 18:33 UTC, 1Evolve commented on client/camera.lua
> +        local CamRot = GetCamRot(securityCam, 2)
done :)

2024-02-19 18:33 UTC, 1Evolve commented on client/camera.lua
> +    cameraId = tonumber(cameraId)
done :)

2024-02-19 18:33 UTC, 1Evolve commented on client/camera.lua
> +            table.insert(menu.options, {
done :)

2024-02-19 18:33 UTC, 1Evolve commented on client/camera.lua
> +    ClearPedTasks(PlayerPedId())
done :)

2024-02-25 12:00 UTC, BerkieBb commented
Check remaining comments

2024-02-25 17:54 UTC, 1Evolve commented on client/camera.lua
> +        Wait(1)
done :)

2024-02-25 18:02 UTC, 1Evolve commented on config/client.lua
> +        [49] = {coords = vec4(458.513, -1017.173, 31.428, 53.63), label = 'Los Santos Police Department - CAM#2', isOnline = true},
yes remove number now

2024-03-19 09:46 UTC, 1Evolve commented
Is there any response to the request?

2024-03-19 09:46 UTC, 1Evolve commented
If it does not fit the idea of the project, please close the request

2024-03-19 09:47 UTC, 1Evolve commented
three months

2024-03-19 15:12 UTC, Manason requested changes
Please fix the lint errors.

It looks like there are several new features and refactors in this PR. If you want faster reviews, consider breaking up your PRs into smaller bite sized chunks of one new feature, or one refactor. These large PRs can be difficult and time consuming to review with lots of back and forth comments.

2024-03-19 15:12 UTC, Manason commented on server/commands.lua
> +    TriggerClientEvent('police:client:showCamera', source)
Would this be better as a callback? I like to use events only when we expect/want multiple event handlers, but this seems to be more like a network function call use of events.

2024-03-19 15:12 UTC, Manason commented on client/camera.lua
> +    tabletProp = CreateObject(`prop_cs_tablet`, 0.0, 0.0, 0.0, true, true, false)
We shouldn't be creating networked props on the client as it is not compliant with entity lockdown mode. Instead, create it on the server.

2024-03-19 15:12 UTC, Manason commented on client/camera.lua
Use https://overextended.dev/ox_lib/Modules/Streaming/Client#librequestscaleformmovie

2024-03-19 15:12 UTC, Manason commented on client/job.lua
> +    return playerJob.type ~= 'leo' or playerJob.grade.level >= (level or 0) or playerJob.onduty == (onduty == nil and true or onduty)
```suggestion
    return playerJob.type == 'leo' and playerJob.grade.level >= (level or 0) and playerJob.onduty == (onduty == nil and true or onduty)
```

2024-03-19 19:39 UTC, 1Evolve commented on client/camera.lua
done :)

2024-03-19 19:39 UTC, 1Evolve commented on client/job.lua
> +    return playerJob.type ~= 'leo' or playerJob.grade.level >= (level or 0) or playerJob.onduty == (onduty == nil and true or onduty)
thank you for edit :)

2024-03-19 19:40 UTC, 1Evolve commented on client/main.lua
> +        end
I think it works better now thank u for sugg

2024-05-02 23:07 UTC, BerkieBb commented on server/commands.lua
> +    TriggerClientEvent('police:client:showCamera', source)
A callback is only used when you expect to receive something back, otherwise you use events. So this is correct.

2024-05-02 23:08 UTC, BerkieBb commented on server/commands.lua
> +    TriggerClientEvent('police:client:showCamera', source)
Callback inherently are also just events, so it won't make a difference if you do use it aside from you using more resources to do the same thing

2024-05-02 23:10 UTC, BerkieBb commented on client/camera.lua
> +    tabletProp = CreateObject(`prop_cs_tablet`, 0.0, 0.0, 0.0, true, true, false)
@1Evolve just this one and you should be good

2024-05-02 23:13 UTC, 1Evolve commented
Completed 4 months ago
You can delete the withdrawal request
I'm no longer as enthusiastic as I started out with

2024-06-01 16:14 UTC, closed without merging

2024-06-01 16:14 UTC, mafewtm commented
Closed as requested.