replace to ox_lib disableControls
Qbox-project/qbx_policejob pull request #86
Opened 2024-02-16 08:22 UTC by bicatcho11

## Description

replace to ox_lib disableControls

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-16 22:24 UTC, FjamZoo approved these changes

2024-02-16 22:27 UTC, Manason requested changes
This is incorrect. See documentation on use of https://overextended.dev/ox_lib/Modules/DisableControls/Client#libdisablecontrols

You need to add controls to disable outside of the loop, and then call lib.disableControls() on every frame after.

2024-05-02 23:05 UTC, BerkieBb commented
Still incorrect usage, read the documentation on how to actually disable the controls, this just adds them to a table and does nothing else

2024-06-01 12:22 UTC, closed without merging

2024-06-01 12:22 UTC, ArturMichalak commented
Done with https://github.com/Qbox-project/qbx_policejob/pull/112/files#diff-98feec43e9172cd772d9c4664c809209273214b8ebf4f48e74f6305f39d921e5